using UnityEngine;


public class GrabAction : MonoBehaviour
{
    public Leap.GrabDetector grabDetector;
    private bool wasGrabbingLastFrame = false;

    void Update()
    {
        if (grabDetector == null)
            return;

        // Comenz贸 a agarrar este frame
        if (grabDetector.GrabStartedThisFrame)
        {
            Debug.Log("[GrabLogger] Mano comenz贸 a agarrar");
            Debug.Log("GrabStrength: " + grabDetector.IsGrabbing);
            wasGrabbingLastFrame = true;
        }
        // Solt贸 el objeto
        else if (wasGrabbingLastFrame && !grabDetector.IsGrabbing)
        {
            Debug.Log("[GrabLogger] Mano solt贸 el objeto");
            Debug.Log("GrabStrength: " + grabDetector.IsGrabbing);
            wasGrabbingLastFrame = false;
        }
    }
}

